// privacy policy page
export default function PrivacyPolicy() {
  return (
    <div className="privacy-policy">
      <h1 className="privacy-policy__title">Privacy Policy</h1>

      <p>Your privacy is important to me. This privacy policy outlines the types of personal information I receive and collect when you visit my website and how I safeguard your information.</p>

      <h2 className="privacy-policy__heading">Personal Information I Collect</h2>
      <p>
        This site collects non-personally identifiable information, such as the type of browser you're using, the type of operating system you're using, and the domain name of your internet service provider. This data is used for internal purposes
        only and is not shared with third parties.
      </p>

      <h2 className="privacy-policy__heading">Google Analytics</h2>
      <p>
        This site uses Google Analytics to track and analyze the usage of my website. Google Analytics collects information such as how often users visit my site, what pages they visit, and what other sites they used before coming to my site. The
        information generated by the Google Analytics cookies about your use of my website, including your IP address, will be transmitted to and stored by Google.
      </p>
      <p>
        Google Analytics does not identify individual users or associate your IP address with any other data held by Google. I use the information I get from Google Analytics only to improve my website. Google's ability to use and share information
        collected by Google Analytics about your visits to this site is restricted by the Google Analytics Terms of Service and the Google Privacy Policy. You can prevent Google Analytics from recognizing you on return visits to this site by
        disabling cookies on your browser.
      </p>

      <h2 className="privacy-policy__heading">Cookies</h2>
      <p>I may use cookies to store information, such as your personal preferences when you visit my site. This could include the ability to remember your login information or your user preferences.</p>

      <h2 className="privacy-policy__heading">Third-Party Advertisers</h2>
      <p>I do not use third-party advertisers on my website.</p>

      <h2 className="privacy-policy__heading">Links to Other Websites </h2>
      <p>
        My website may contain links to other websites of interest. However, once you have used these links to leave our site, you should note that I do not have any control over that other website. Therefore, I cannot be responsible for the
        protection and privacy of any information that you provide while visiting such sites, and such sites are not governed by this privacy policy. You should exercise caution and look at the privacy policy applicable to the website in question.
      </p>

      <h2 className="privacy-policy__heading">Changes to This Privacy Policy</h2>
      <p>I may update this privacy policy from time to time to reflect changes to our information practices. I encourage you to periodically review this page for the latest information on our privacy practices.</p>
      <p>
        If you have any questions or concerns about our privacy policy, please contact us at:{" "}
        <span className="privacy-policy__link">
          <a href="mailto:keithbillingsbusiness@gmail.com">keithbillingsbusiness@gmail.com</a>
        </span>
      </p>
    </div>
  );
}
